### ISSUE TITLE
前端样式修改

### ISSUE THREAD

**Issue by liu946** [liu946/yanhandb#5]
1. 点击小黑板查看详细内容    改为    详细
2. judge output -> 分析 和 依据
3. 所有数值输出保留两位小数，长度不要太长
4. 名字 -> 统计项 这一列不要缩，多长都显示
5. 所有 NaN显示空字符串
6. 所有没有score的字段显示为灰色，不主要显示
7. 最下端的bottom bar显示有些问题，我这边显示的很高，而且滑到最下端的时候是可以滚动的，会把topbar滑出去。注意一下适配，实在不行就用fream卡

**Comment by VachelHU** [comment]
修改了，
第6项要不要灰色没关系吧，反正没有值就是空的
第7项不太清楚什么问题，我这没有出现
